---
- name: "L3_24-to-16"
  
  stream:
    action_count: 0
    enabled: true
    flags: 2
    flow_stats:
      enabled: true
      rule_type: "stats"
      stream_id: 0
    isg: 0.0
    mode:
      rate:
        type: "pps"
        value: 3500000.0
      type: "continuous"
      total_pkts: 1
      pkts_per_burst: 1
      ibg: 0.0
      count: 1
    
    packet:
      binary: "AAEAAAABAgAAAAAACABFAADuBNIAAH8AdjoYAAAAEAAAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna"
      meta: "eyJwcm90b2NvbF9zZWxlY3Rpb24iOnsiaXNfaXB2NF9zZWxlY3RlZCI6dHJ1ZSwiaXNfdGNwX3NlbGVjdGVkIjpmYWxzZSwiaXNfdWRwX3NlbGVjdGVkIjpmYWxzZSwiaXNfcGF0dGVybl9zZWxlY3RlZCI6dHJ1ZSwiaXNfdGFnZ2VkX3ZsYW5fc2VsZWN0ZWQiOmZhbHNlLCJmcmFtZV9sZW5ndGhfdHlwZSI6IkZpeGVkIiwiZnJhbWVfbGVuZ3RoIjoiMjU2IiwibWluX2xlbmd0aCI6IjY0IiwibWF4X2xlbmd0aCI6IjE1MTgifSwiZXRoZXJuZXQiOnsidHlwZSI6IjA4MDAiLCJpc19vdmVycmlkZSI6dHJ1ZX0sIm1hYyI6eyJzb3VyY2UiOnsiYWRkcmVzcyI6IjAyOjAwOjAwOjAwOjAwOjAwIiwibW9kZSI6IlRSZXggQ29uZmlnIiwic3RlcCI6IjEiLCJjb3VudCI6IjkwMDAifSwiZGVzdGluYXRpb24iOnsiYWRkcmVzcyI6IjAwOjAxOjAwOjAwOjAwOjAxIiwibW9kZSI6IkZpeGVkIiwic3RlcCI6IjEiLCJjb3VudCI6IjkwMDAifX0sImlwdjQiOnsic291cmNlIjp7ImFkZHJlc3MiOiIyNC4wLjAuMCIsIm1vZGUiOiJJbmNyZW1lbnQgSG9zdCIsInN0ZXAiOiIxIiwiY291bnQiOiI1MDAwMDAifSwiZGVzdGluYXRpb24iOnsiYWRkcmVzcyI6IjE2LjAuMC4wIiwibW9kZSI6IkluY3JlbWVudCBIb3N0Iiwic3RlcCI6IjEiLCJjb3VudCI6IjUwMDAwMCJ9fSwidGNwIjp7ImlzX292ZXJyaWRlX2RzdF9wb3J0IjpmYWxzZSwiaXNfdXJnIjpmYWxzZSwiaXNfYWNrIjpmYWxzZSwiaXNfcHNoIjpmYWxzZSwiaXNfcnN0IjpmYWxzZSwiaXNfc3luYyI6ZmFsc2UsImlzX2ZpbiI6ZmFsc2UsImNoZWNrc3VtIjoiQjNFMyIsImRzdF9wb3J0IjoiMTAyNSIsInNyY19wb3J0IjoiMTAyNSIsImlzX292ZXJyaWRlX3NyY19wb3J0IjpmYWxzZSwiYWNrX251bWJlciI6IjAiLCJpc19vdmVycmlkZV9jaGVja3N1bSI6ZmFsc2UsInVyZ2VudF9wb2ludGVyIjoiMCIsIndpbmRvdyI6IjEwMjQiLCJzZXF1ZW5jZV9udW1iZXIiOiIxMjkwMTgifSwidWRwIjp7ImlzX292ZXJyaWRlX2RzdF9wb3J0IjpmYWxzZSwibGVuZ3RoIjoiMjYiLCJpc19vdmVycmlkZV9sZW5ndGgiOmZhbHNlLCJjaGVja3N1bSI6IkZGQkEiLCJkc3RfcG9ydCI6IjEwMjUiLCJzcmNfcG9ydCI6IjEwMjUiLCJpc19vdmVycmlkZV9zcmNfcG9ydCI6ZmFsc2UsImlzX292ZXJyaWRlX2NoZWNrc3VtIjpmYWxzZX0sInBheWxvYWQiOnsidHlwZSI6IkluY3JlbWVudCBCeXRlIiwicGF0dGVybiI6IjAwIn0sInZsYW4iOnsicHJpb3JpdHkiOiIwIiwidHBfaWQiOiJGRkZGIiwiY2ZpIjoiMCIsInZfaWQiOiIwIiwiaXNfb3ZlcnJpZGVfdHBfaWQiOmZhbHNlfSwiYWR2YW5zZWRfcHJvcGVydGllcyI6eyJjYWNoZV9zaXplX3R5cGUiOiJBdXRvIiwiY2FjaGVfdmFsdWUiOiI1MDAwIn0sIm1vZGVsX3ZlcnNpb24iOiIxLjAifQ=="
      model: ""
    self_start: true
    advanced_mode: false
    vm:
      split_by_var: "ip_src"
      instructions:
      - init_value: 268435456
        min_value: 268435456
        max_value: 268935455
        name: "ip_dest"
        op: "inc"
        size: 4
        step: 1
        type: "flow_var"
      - add_value: 0
        is_big_endian: true
        name: "ip_dest"
        pkt_offset: 30
        type: "write_flow_var"
      - init_value: 402653184
        min_value: 402653184
        max_value: 403153183
        name: "ip_src"
        op: "inc"
        size: 4
        step: 1
        type: "flow_var"
      - add_value: 0
        is_big_endian: true
        name: "ip_src"
        pkt_offset: 26
        type: "write_flow_var"
      - pkt_offset: 14
        type: "fix_checksum_ipv4"
      cache_size: 5000
  stream_id: 0
